query FIND_USER_BY_ID($findByIdId: ID!) {
  findById(id: $findByIdId) {
    __typename
    ... on ErrorResponse {
      code
      error
      success
    }
    ... on UserMutationResponse {
      code
      message
      success
      user {
        email
        id
      }
    }
  }
}

mutation CREATE_USER($userInput: UserInput!) {
  createUser(userInput: $userInput) {
    __typename
    ... on UserAuthResponse {
      code
      message
      success
      token
      user {
        id
        email
        userName
      }
    }
    ... on ErrorResponse {
      success
      code
      error
    }
  }
}
